services:
    api-rails: 
        build:
            context: apiRails/
            # target: development
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        container_name: api-rails
        depends_on:
            - db
        ports: 
            - "3000:3000"
        volumes: 
            - ".:/api-rails"
    db:
        image: keinos/sqlite3:latest
        stdin_open: true
        tty: true
        volumes:
            - ./db/:/root/db/
    api-rails-test: 
        build:
            context: apiRails/
            # target: development
        command: bundle exec web rails test
        container_name: api-rails-test
        volumes: 
            - ".:/api-rails-test"

